# This file was generated by GoReleaser. DO NOT EDIT.
class ReleaseTest < Formula
  desc ""
  homepage "https://www.ory.sh"
  url "https://github.com/aeneasr/release-test/releases/download/v0.0.17/release-test_0.0.17_macOS_64-bit.tar.gz"
  version "0.0.17"
  sha256 "fe8697b5832bfaccba30cfed73994a3800a636b03816dc39d980002734cd4881"

  def install
    bin.install "release-test"
  end
end
