# This file was generated by GoReleaser. DO NOT EDIT.
class ReleaseTest < Formula
  desc ""
  homepage "https://www.ory.sh"
  url "https://github.com/aeneasr/release-test/releases/download/v0.0.11/release-test_0.0.11_macOS_64-bit.tar.gz"
  version "0.0.11"
  sha256 "5d974b4a6b500dfe48e81d1439ed6607102140dd4151ff7edd68f4c220d8f2a5"

  def install
    bin.install "release-test"
  end
end
